USE [master]
GO
/****** Object:  Database [Bitcoin]    Script Date: 5. 5. 2024 17:05:01 ******/
CREATE DATABASE [Bitcoin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bitcoin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Bitcoin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bitcoin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Bitcoin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Bitcoin] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bitcoin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Bitcoin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Bitcoin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Bitcoin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Bitcoin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Bitcoin] SET ARITHABORT OFF 
GO
ALTER DATABASE [Bitcoin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Bitcoin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Bitcoin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Bitcoin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Bitcoin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Bitcoin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Bitcoin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Bitcoin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Bitcoin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Bitcoin] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Bitcoin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Bitcoin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Bitcoin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Bitcoin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Bitcoin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Bitcoin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Bitcoin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Bitcoin] SET RECOVERY FULL 
GO
ALTER DATABASE [Bitcoin] SET  MULTI_USER 
GO
ALTER DATABASE [Bitcoin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Bitcoin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Bitcoin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Bitcoin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Bitcoin] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Bitcoin] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Bitcoin', N'ON'
GO
ALTER DATABASE [Bitcoin] SET QUERY_STORE = ON
GO
ALTER DATABASE [Bitcoin] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Bitcoin]
GO
/****** Object:  User [BitcoinUser]    Script Date: 5. 5. 2024 17:05:01 ******/
CREATE USER [BitcoinUser] FOR LOGIN [BitcoinUser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [BitcoinUser]
GO
ALTER ROLE [db_datareader] ADD MEMBER [BitcoinUser]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [BitcoinUser]
GO
/****** Object:  Table [dbo].[BitcoinRate]    Script Date: 5. 5. 2024 17:05:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BitcoinRate](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BTC_EUR] [decimal](18, 3) NOT NULL,
	[CZK_EUR] [decimal](18, 3) NOT NULL,
	[BTC_CZK] [decimal](18, 3) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[DownloadedDate] [datetime] NOT NULL,
	[Note] [nchar](3000) NULL,
 CONSTRAINT [PK_BitcoinRate] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Bitcoin] SET  READ_WRITE 
GO
